### ISSUE TITLE
Never injects itself?

### ISSUE THREAD

**Issue by QuakeSinatra** [atom0s/rMod#4]
rMod runs .. and OK's everything tells me have fun and then launches KOAR but never can activate the console. I have remapped to other key binds using the info given. tried ~ (default) tried INSERT tried SPACE .. disabled anything i thought might be getting in the way (MalwareBytes,Steam overlay). It seams that i am the ONLY one with this problem because everything i find even remotely close to the problem of not getting the in game console seems to only happen after trying to bind it to something else and getting it slightly wrong. I just never seem to get the console at all... no error or anything else i can find stating that there even was a problem...So I am waving the white flag could someone please tell me what i am doing wrong? Windows 10 Pro updated to current and steam and KOAR updated to current.. not even sure what else would be pertinent or helpful..working off 1.0.0.0.7 fully updated and modified my game path to point to the steam path, havent changed much else except what i thought might help and always changed it back when it doesnt help.

**Comment by atom0s** [comment]
First and foremost, make sure you have the required redistributable file from here:
https://aka.ms/vs/16/release/vc_redist.x86.exe

Next, be sure you followed the information found here:
https://github.com/KoA-rMod/rMod/wiki/2.-How-To-Install-or-Update-rMod

When you inject and play the game, does the game start and do you see a popup like this?
![pic](https://upload.worldofplayers.de/files11/koastart02.jpg)

If you do not see that popup, then rMod did not inject properly or is not able to properly render. If you do see it and the console still doesn't show, it's usually due to a different keyboard layout. You can edit the default.txt script to change the default console bind. I'd suggest trying something basic like the F1 key instead if it does not work still just to see if that will work, then adjust to a better suitable key once you can confirm it is working.

**Comment by QuakeSinatra** [comment]
First off : Thank you so much for your work on this project,
reinstalled the redistrib / it let me install without a repair prompt so i was hopeful..
still do NOT get anything like the 
pic
you show.. so it seems to not being injected..
tried the keybinding to SPACE END as well as the tilde no joy in mudville.
is there any logging or anything like a log i can look for ?
I am fully of the opinion that it is something silly that i have set up on my PC thats causing it to not work...or something i did security wise or setup wise ... but honestly I cant think of much that i have changed (at least recently anyway) but my PC is what I typically used for staging and testing for my IT Security job until i retired.. going to set up a test machine and get everything installed on there.. but you have done so much to make it dead simple to install/configure i dont see that changing too much all i will know for sure is that its a pristine install. I will comment if i make any progress toward a solution.
Thank you again!

**Comment by atom0s** [comment]
Very odd. Some other things to ask/check:

 - Are you using the Steam version or the Origin version of the game?
 - Are you running the game via Steam or through rMod's launcher?
 - Is Steam running before you try to use rMod?
 - Does the game load after using rMod's launcher at all?

Double-check and make sure your path is correct inside of the rmod.ini file. (Be sure to use an editor such as Notepad++ or similar to edit the file properly.)

The path should look something like this:
```ini
[loader]
path        = D:\Games\Steam\SteamApps\common\KOAReckoning\Reckoning.exe
steam       = 1
steamappid  = 102500
```

Adjust accordingly to where you have the game installed. Steam info should remain the same. rMod used to work as-is with the Origin version of the game, but since Origin has updated a lot over the years, people have reported that no longer is the case. I do not own the game on Origin and do not use it either, so it is not something I can test against personally.

As for logging, currently no. Just what the loader outputs is it.

**Comment by atom0s** [comment]
Oh, something else to add. If you use any proxies or shader alterations like ReShade, disable/remove those first.

**Comment by QuakeSinatra** [comment]
Brand new install (VM) so still using the same hardware for the most part .. but clean install of Steam and KOATR and rMod

so no shaders. 

Path is correct 

running rMod out of C:\games\rMod because i have had issues with older games not dealing  the Win10 perms on the Program Files directory..

Running straight from rMod (tried steam open already and steam closed)

Using steam version.

loader shows all OK and then launches the game.

setting up an old pc today and starting COMPLETELY from scratch will post results.
Thanks again for all the help hopefully it will result in a new solution for whatever one off weirdness i am having.

**Comment by atom0s** [comment]
Could be an issue with the VM's Direct3D support/handling causing it to fail to render properly. Would suggest trying to install the game and rMod on your actual system instead.

**Comment by QuakeSinatra** [comment]
to clarify:
1st run was on my main pc.
much troubleshooting ensued
2nd run was in a VM on my main machine
3rd run was a (rebuilt from parts) PC.
on that 3rd run PC I:

installed/updated win10
installed notepad++
installed Steam
installed KOAR
installed rMod (at c:\rMod )
installed visual C req
installed 7zip
updated rMod
Changed the rMod.ini to the correct path
ran rMod (as administrator)


WORKS FINE!!!!

so ultimately something on my old work pc (where i did datacenter security) has had some modifications done to it that werent properly removed or had some software installed that changed something integral to rMod most everything else works fine and the few things that dont i am able to overcome with a bit of tinkering.. its also my Dual boot(sometimes tri-boot) linux development PC so i am reticent to reinstall and reconfigure everything ;)

**Comment by atom0s** [comment]
Glad to hear you got it working! :)
